name: Docker Image CI
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v32
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done
    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v32
      with:
        files: |
          Dockerfile
          templates/**
    - name: Build the Docker image
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: docker build -t chrborg/rpi-monitor:latest .
    - name: Login in Docker Hub
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - name: Publish the Docker image
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: docker push chrborg/rpi-monitor:latest
